lines = [
    "# squish/kernels/mojo/kernels/magic_pig_score.mojo\n",
    "# MagicPIG LSH-bucketed attention score computation kernel.\n",
    "#\n",
    "# Parallelises over H heads.\n",
    "# Reference: He et al., arXiv 2410.16179, 2024.\n",
    "\n",
    "from algorithm import parallelize\n",
    "from math import sqrt\n",
    "\n",
    "\n",
    "fn magic_pig_score_kernel(\n",
    "    q_ptr:    UnsafePointer[Float32],\n",
    "    k_ptr:    UnsafePointer[Float32],\n",
    "    v_ptr:    UnsafePointer[Float32],\n",
    "    out_ptr:  UnsafePointer[Float32],\n",
    "    h:        Int,\n",
    "    tq:       Int,\n",
    "    seq_len:  Int,\n",
    "    d:        Int,\n",
    "):\n",
    "    # Parallel over heads; sequential query loop per head; softmax + GEMV over V.\n",
    "    @parameter\n",
    "    fn process_head(hi: Int):\n",
    "        var inv_scale = Float32(1.0) / sqrt(Float32(d))\n",
    "        var logits = UnsafePointer[Float32].alloc(seq_len)\n",
    "        for qi in range(tq):\n",
    "            for si in range(seq_len):\n",
    "                var dot = Float32(0.0)\n",
    "                for j in range(d):\n",
    "                    dot += q_ptr[hi * tq * d + qi * d + j] * k_ptr[hi * seq_len * d + si * d + j]\n",
    "                logits[si] = dot * inv_scale\n",
    "            var max_l = logits[0]\n",
    "            for si in range(1, seq_len):\n",
    "                if logits[si] > max_l:\n",
    "                    max_l = logits[si]\n",
    "            var sum_exp = Float32(0.0)\n",
    "            for si in range(seq_len):\n",
    "                var x = logits[si] - max_l\n",
    "                var ex = Float32(1.0)\n",
    "                var term = Float32(1.0)\n",
    "                for tk in range(1, 12):\n",
    "                    term = term * x / Float32(tk)\n",
    "                    ex += term\n",
    "                ex = ex if ex > Float32(0.0) else Float32(0.0)\n",
    "                logits[si] = ex\n",
    "                sum_exp += ex\n",
    "            if sum_exp < Float32(1e-8):\n",
    "                sum_exp = Float32(1e-8)\n",
    "            for si in range(seq_len):\n",
    "                logits[si] = logits[si] / sum_exp\n",
    "            for j in range(d):\n",
    "                out_ptr[hi * tq * d + qi * d + j] = Float32(0.0)\n",
    "            for si in range(seq_len):\n",
    "                for j in range(d):\n",
    "                    out_ptr[hi * tq * d + qi * d + j] += logits[si] * v_ptr[hi * seq_len * d + si * d + j]\n",
    "        logits.free()\n",
    "\n",
    "    parallelize[process_head](h)\n",
]

with open('/Users/wscholl/squish/squish/kernels/mojo/kernels/magic_pig_score.mojo', 'w') as f:
    f.writelines(lines)
print('written ok')
